### ISSUE TITLE
As a site user I want to be able to view the navbar from every page so that I can navigate easily between pages

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#1]
EPIC: <Viewing and Navigation>

As a **site user** I want to be able to **view the navbar from every page** so that I can **navigate easily between pages**

**Acceptance Criteria**
- [x] implement navigation view across all pages
- [x] update user's view of navbar to reflect user's login status

**Tasks**
- [x] Task 1: build a navigation template
- [x] Task 2: make the navigation template available across every page
