### ISSUE TITLE
Navigation links

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#10]
As a **site user** I want to be able to **navigate through pages quickly** so that I can **view content seamlessly without page refresh**

**Acceptance Criteria**
- [x] implement links for each Category in navigation bar
- [x] all pages on the site can be reached by a link from each other page

**Tasks**
- [x] Task 1: Add links to each Category in the navigation bar
- [x] Task 2: Add the url for each page to the site's urls.py files
