### ISSUE TITLE
View Products list

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#11]
EPIC: <epic>

As a **site user** I want to be able to **view a list of products** so that I can **select one or some to purchase**

**Acceptance Criteria**
- [x] all products can be viewed in a responsive grid
- [x] clicking 'Add to Cart' button should add the item to the Shopping Cart

**Tasks**
- [x] Task 1: Build a Products App
- [x] Task 2: Create a Products template page
- [x] Task 3: Create a loop to render each product individually to the Products page in a list
- [x] Task 4: Make the list of products scrollable
- [x] Task 5: Render a clickable button with a Product to enable the user add the item to their Shopping Cart
- [x] Task 6: Add a list of products to the fixtures folder via admin

**Comment by MoniMurray** [comment]
products and categories json files created via admin
