### ISSUE TITLE
View number of items in Shopping Cart

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#12]
As a **site user** I want to be able to **view the number of items in my shopping cart** so that I can **know how many items I have selected for purchase**

**Acceptance Criteria**
- [x] view the number of the items in the Shopping Cart over the Shopping Cart icon

**Tasks**
- [x] Task 1: Add an icon of  Shopping Cart to the Nav bar
- [x] Task 2: Create a counter to display an integer of the total number of products in the Shopping Cart session

**Comment by MoniMurray** [comment]
Works well at large screen size
