### ISSUE TITLE
View where to Register/Login

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#13]
EPIC: <epic>

As a **site user** I want to be able to **see where the Register and Login options are** so that I can **Register/Login**

**Acceptance Criteria**
- [x] view options to Register or Login to My Account in navigation bar

**Tasks**
- [x] Task 1: Create drop down list on 'My Account' in the navigation bar to see 'Register' and 'Login' links
- [x] Task 2: Create the link to open the relevant Django allauth default account template page and make 'Register' and 'Login' links to launch the relevant page

**Comment by MoniMurray** [comment]
Works well on desktop and mobile view.
