### ISSUE TITLE
New User Registration

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#14]
EPIC: <epic>

As a **site user** I want to be able to **easily register for a personal user account** so that I can **have a personal account and be able to view my account content, previous orders and save my billing and shipping details**

**Acceptance Criteria**
- [x] Register link launches User Registration page to anonymous users
- [x] Allauth default registration form loads
- [x] New user can submit the completed form when required fields are completed
- [x] Newly registered user receives user feedback on successfully registering

**Tasks**
- [x] Task 1: Link 'Register' on nav bar to Account Registration Django allauth template page
- [x] Task 2: All required fields give appropriate response to user if left blank
- [x] Task 3: All input fields accept user input
- [x] Task 4: Register button on allauth template page give appropriate user feedback response
