### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#15]
EPIC: <epic>

As a **site user** I want to be able to **login to my account** so that I can **access, view and edit my personal account information**

**Acceptance Criteria**
- [x] Login link launches User Login page to anonymous users
- [x] registered user can input their data in the required fields and be redirected to logged in Home page

**Tasks**
- [x] Task 1: Link 'Login' on nav bar and Registration template page to Login template page
- [x] Task 2: All required fields give appropriate response to user if left blank
- [x] Task 3: All input fields accept user input
- [x] Task 4: Login button on Login template page launches Home page with logged-in navigation bar with access to user's personal account information
