### ISSUE TITLE
User Logout

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#16]
As a **site user** I want to be able to **logout of my account** so that I can **log out and secure my personal account information when not using the store**

**Acceptance Criteria**
- [x] Logout link logs the User out

**Tasks**
- [x] Task 1: Link 'Logout' on logged-in user's navigation bar view returns success message ""You have signed out""
- [x] Task 2: Home page view returns to limited unauthorised user view."
