### ISSUE TITLE
Logged-in User My Account

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#17]
As a **logged in user** I want to be able to **edit my personal and shipping details** so that I can **keep my account profile up to date**

**Acceptance Criteria**
- [x] Access My Account information via navigation bar
- [x] Edit My Account personal details
- [x] Save changes to My Account personal details
- [x] See a list of previous purchases

**Tasks**
- [x] Task 1: Build a My Account app
- [x] Task 2: Create a My Account template page
- [x] Task 3: Render the authenticated User's editable shipping details to the My Account template in a form
- [x] Task 4: Save any edits made to the User's profile to the database
