### ISSUE TITLE
Sort products using pre-defined criteria

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#18]
EPIC: <epic>

As a **site user** I want to be able to **sort the available products** so that I can **identify highly rated, low/high priced items**

**Acceptance Criteria**
- [x] Sort product view by Highly rated, or by price low/high, high/low

**Tasks**
- [x] Task 1: Add database query options to the nav bar search function
- [x] Task 2: Add query to sort products through drop-down choices - Sort by rating, Sort by price descending, Sort by price ascending"

**Comment by MoniMurray** [comment]
Sort drop-down working well
