### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#2]
EPIC: <Home page>

As a **first time site user** I want to be able to **see a colourful, robust and intuitive landing page** so that I can **understand what the site sells and be encouraged to make a purchase**

**Acceptance Criteria**
- [ ] implement fully functioning, fully responsive, grid-based landing page 
- [ ] from the layout, typography and imagery, intuit website's purpose 

**Tasks**
- [x] Task 1: Build a Home page app
- [x] Task 2: Create the Home page template
- [x] Task 3: Add the Home page url to the main url.py
- [x] Task 4: Add grid based bootstrap to layout the products in a responsive way
- [x] Task 5. Include a site image which conveys the business purpose, ie. bookstore
