### ISSUE TITLE
View Products by Author

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#20]
As a **site user** I want to be able to **view products by author** so that I can **select works by the same author**

**Acceptance Criteria**
- [x] User can use Search bar to search by Author to view a list of items available to purchase by that Author

**Tasks**
- [x] Task 1: create a relationship between products and author in the database
- [x] Task 2: render the list of the products by the searched for Author name using template logic, or a message 'Nothin turned up'

**Comment by MoniMurray** [comment]
Author is a ForeignKey in the Product model, so has to be searched as an author object rather than as a string dataset. use get_object_or_404 for the author and then use a simple filter.

1. You have a form which is providing a string to the view

2. You have a view which is using the string to create a filter

3. You filter the database by said filter and return the context to display.

Test using print statements throughout at each point of the all_products.

**Comment by MoniMurray** [comment]
I used Q(author__name__icontains=query) in the end, to query the name field in the author model.
