### ISSUE TITLE
View number of Searched for items

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#21]
As a **site user** I want to be able to **view what I have searched** so that I can **see whether what I want is available in the store and the number of the search results**

**Acceptance Criteria**
- [x] User can Search the store for items available to purchase by Category, Title or Author
- [x] User's search response is a list of items, and the number of the returned items, or a message 'Nothing turned up'"

**Tasks**
- [x] Task 1: Query the database for Category, Author and Title
- [x] Task 2: Render the returned dataset to the Products template in a list , or a message 'Nothing turned up'
- [x] Task 3: Clear the search input box after each search to enable User make another database query

**Comment by MoniMurray** [comment]
Used the phrase "0 Products found for ' '" instead of 'Nothing turned up'

**Comment by MoniMurray** [comment]
Added 'description' field as a search term also
