### ISSUE TITLE
Add an item to my Shopping Cart

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#22]
EPIC: <epic>

As a **site user** I want to be able to **add an item to my shopping cart** so that I can **make a purchase**

**Acceptance Criteria**
- [x] User can click on 'Add to Cart' button on any product item
- [x] Item is added to the User's Shopping Cart session"

**Tasks**
- [x] Task 1: Build a Shopping Cart app
- [x] Task 2: Create a Shopping Cart template
- [x] Task 3: render the items selected for purchase to the Shopping Cart Template as lineitems with Product Image, Product name, 
Product price and quantity picker, with Shopping Cart Total
