### ISSUE TITLE
View contents of the Shopping Cart

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#24]
As a **site user** I want to be able to **view the contents of the shopping cart** so that I can **see the total cost of what I have selected**

**Acceptance Criteria**
- [x] User can click on the Shopping Cart icon to view their Shopping Cart items
- [x] User can see each selected item, and see the total cost of their shopping

**Tasks**
- [x] Task 1: Add a link to the Shopping Cart favicon to launch Shopping Cart template when clicked
- [x] Task 2: View each item selected for purchase as lineitems with Product name, Product Image, Quantity, Product price, Shopping Cart sub-total, shipping cost and Cart Total
