### ISSUE TITLE
Adjust line item quantity in Shopping Cart

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#25]
EPIC: <epic>

As a **site user** I want to be able to **adjust the quantity of any item in the shopping cart** so that I can **increase or decrease the quantity of an item for purchase**

**Acceptance Criteria**
- [x] User can increase and decrease the lineitem quantity of any item in the Shopping Cart between 1-5

**Tasks**
- [x] Task 1: Create a number picker and limit the number picker to min 1 and max 5
- [x] Task 2: Increase/decrease the lineitem price, sub-total and Cart total based on any increase/decrease to quantity

**Comment by MoniMurray** [comment]
Bug - though limited quantity works on product detail page, the limits are not working in the bag and need to be adjusted. Not yet fixed
