### ISSUE TITLE
Delete item from Shopping Cart

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#26]
EPIC: <epic>

As a **site user** I want to be able to **delete an item from my shopping cart** so that I can **remove it for purchase**

**Acceptance Criteria**
- [x] User can remove a lineitem from the shopping cart

**Tasks**
- [x] Task 1: Add a delete link to the Shopping cart lineitems
- [x] Task 2:  Delete an item from the shopping cart, decrease sub-total and Cart total if item is deleted
