### ISSUE TITLE
Checkout and pay

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#27]
EPIC: <epic>

As a **site user** I want to be able to **checkout and pay** so that I can **complete my purchase**

**Acceptance Criteria**
- [x] click 'checkout' button in the shopping cart to launch checkout screen
- [x] view checkout template page pre-loaded with Shopping Cart contents, sub-total, shipping cost, and Total
- [ ] view shipping details form on checkout template page pre-filled with shipping address data if user has made a previous purchase, blank if making a first purchase"

**Tasks**
- [x] Task 1: Build a Checkout app
- [x] Task 2: Create a Checkout template page
- [x] Task 3: Render the items in the Shopping Cart to the Checkout page
- [x] Task 4: Create a Checkout form
- [x] Task 5: Render the Checkout form on the Checkout page
