### ISSUE TITLE
View order confirmation page

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#29]
EPIC: <epic>

As a **site user** I want to be able to **view an order confirmation after checkout** so that I can **review a summary of my successful purchase**

**Acceptance Criteria**
- [x] User can view a brief order confirmation on screen following successful purchase

**Tasks**
- [x] Task 1: Create Order Confirmation template page to allow user see their completed purchase summary
- [x] Task 2: Render the lineitems, quantity, sub-total, shipping cost and Order Total to the template
- [x] Task 3: Add two buttons, 'Logout' and 'Return to Home Page' to enable user control

**Comment by MoniMurray** [comment]
Added 'Logout' and 'Back to our Bestsellers' as it was more appropriate than to return to the Home page.
