### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#3]
EPIC: <Home page>

As a **site user** I want to be able to **see an intuitive favicon on the site name in the browser** so that I can **understand the website's purpose**

**Acceptance Criteria**
- [ ] view a favicon on the browser with the website title
**Tasks**
- [ ] Task 1: Choose an image to use as a favicon
- [ ] Task 2: Use [Favicon.io](http://favicon.io/) website, drag in image and download zip file containing png files of differing sized images
- [ ] Task 3: Import links to head tag in base.html
