### ISSUE TITLE
Site Owner Edit Product

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#34]
As a **site owner/admin user** I want to be able to **edit/update an existing item** so that I can **update product price, description, etc*

**Acceptance Criteria**
- [x] Store owner/admin can click on Edit link on Product page
- [x] Store owner/admin can edit not-unique Product fields and save changes to database

**Tasks**
- [x] Task 1: Edit link under a Product launches pre-filled edit form with all fields from the Product entity in the database, using product's primary key in the logic to generate that view
- [x] Task 2: Enable only certain fields for editing
- [x] Task 3: Save button will update changed product data to the database
