### ISSUE TITLE
Site Owner Delete Product

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#35]
As a **site owner/admin user** I want to be able to **delete an item from the site** so that I can **remove items no longer being stocked by the store**

**Acceptance Criteria**
- [x] Store owner/admin can click on Delete link on Product page
- [x] Store owner/admin can Delete Product from the database

**Tasks**
- [x] Task 1: Delete link with each Product in Store Owner/Admin user restricted view launches feedback in a template with 'Are you sure you want to delete [product name]? With Yes/No buttons
- [x] Task 2: If store owner/admin confirms deletion, return user success message
- [x] Task 3: Changes to the database must be immediately available on the front end to the site user
