### ISSUE TITLE
Newly Registered user Verification Email

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#36]
As a **newly registered user** I want to be able to **receive a verification email upon registering on the site** so that I can **verify my account registration was successful**

**Acceptance Criteria**
- [x] On registering, a User can verify their email address
- [x] A newly registered User can see a feedback message whether they were successful or otherwise

**Tasks**
- [x] Task 1: Email verification
