### ISSUE TITLE
Order Confirmation email

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#37]
As a **logged in user** I want to be able to **receive a confirmation of purchase email** so that I can **review and keep a record of my confirmed order**

**Acceptance Criteria**
- [x] On making a purchase from the store a User can receive an order confirmation to their email address

**Tasks**
- [x] Task 1: Create Order Confirmation template email
- [x] Task 2: issue the Order Confirmation email on successfully making a purchase from the website
