### ISSUE TITLE
Success message on adding Product to Shopping Cart

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#41]
As a **site user** I want to be able to **view on screen notifications when I add a product to shopping cart** so that I can **confirm my action was successful**

**Acceptance Criteria**
- [x] User see's an on-screen message beside the Shopping Cart that a new item was added to the Cart
- [ ] User can click on the 'x' on the message to close the message, controlling the actions"

**Tasks**
- [x] Task 1: Create Toasts sub-folder in Project level Templates folder
- [x] Task 2: Create Success template
- [x] Task 3: In the view, add success message 
- [x] Task 4: Repeat for Toast info, warning and errors

**Comment by MoniMurray** [comment]
Django toast messages framework included throughout the Shopping bag for user feedback
