### ISSUE TITLE
Create base template

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#7]
**Tasks**
- [ ] Task 1: Create a templates folder at project level
- [ ] Task 2: Create a base.html template file
- [ ] Task 3: Insert start template from Bootstrap library
- [ ] Task 4: Organise everything in base.html into blocks in base.html

**Comment by MoniMurray** [comment]
Base template created, divided into blocks, and favicon added
