### ISSUE TITLE
Create Custom 404 error page

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#8]
**Tasks**
- [x] Task 1: Create your 404 handler function
- [x] Task 2: Configure your handler URL
- [x] Task 3: Create your 404.html file
