### ISSUE TITLE
Navigation Search function

### ISSUE THREAD

**Issue by MoniMurray** [MoniMurray/bookworms-et-al#9]
As a **site user** I want to be able to **search by category or author** so that I can **so that I can find products that interest me**

**Acceptance Criteria**
- [x] implement search function in nav bar
- [x] search by category, author and see list of returned results

**Tasks**
- [x] Task 1: add a search bar to the navigation pane
- [x] Task 2: add the functionality to search by book category and/or author
- [x] Task 3: render the search results on screen for user 'Search results for [user search criteria]'
- [x] Task 4: if no result, return message to user 'Nothing turned up'

**Comment by MoniMurray** [comment]
Working well
